# Playbook is: A list plays

- hosts: all
  name: Install Apache and PHP
  become: yes
  tasks:
    - name: Install packages 
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - apache2
          - php
          - mediawiki
          - mariadb-server
          - python3-pymysql
    - name: Grant all privileges to mediawiki user
      community.mysql.mysql_query:
        login_user: root
        query: "GRANT ALL ON mediawiki.* TO 'mediawiki'@'localhost' IDENTIFIED BY 'mediawiki';"
        login_unix_socket: /run/mysqld/mysqld.sock

